stages:
  - build
variables:

cache:
  paths:
  - packages
before_script:
    - mono .paket/paket.exe restore

build:
  stage: build
  image: steinpilz/internal-build:1.0.1
  tags:
    - msbuild15
  script:
    - ./build.sh Build
